### ISSUE TITLE
all tables pull all data before selecting a state

### ISSUE THREAD

**Issue by disabilitybenefitsresource** [modimanz/davestates#7]

**Comment by modimanz** [comment]
Only Nationwide and United States data should show now before selecting a state.   This should only be occurring on the Single View of a statemap.

**Comment by disabilitybenefitsresource** [comment]
is nationwide going to be on top or bottom?  It doesn't matter to me.  I made two graphics but want to but up the correct one.

**Comment by modimanz** [comment]
Fixed
